// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Card$ReactHooksTemplate = require("./Card.bs.js");

var greekGodsArray = /* array */[
  {
    name: "Zeus",
    desc: "Zeus is the sky and thunder god in ancient Greek religion, who rules as king of the gods of Mount Olympus"
  },
  {
    name: "Ares",
    desc: "Ares is the Greek god of war. He is one of the Twelve Olympians, the son of Zeus and Hera. In Greek literature, he often represents the physical or violent and untamed aspect of war"
  }
];

function Base(Props) {
  var greekGods = $$Array.map((function (g) {
          return React.createElement(Card$ReactHooksTemplate.make, {
                      god: g
                    });
        }), greekGodsArray);
  return React.createElement("div", {
              className: "container",
              style: {
                paddingTop: "15px"
              }
            }, greekGods);
}

var make = Base;

exports.greekGodsArray = greekGodsArray;
exports.make = make;
/* react Not a pure module */
