// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Card(Props) {
  var god = Props.god;
  return React.createElement("div", {
              className: "card",
              style: {
                width: "18rem"
              }
            }, React.createElement("div", {
                  className: "card-body"
                }, React.createElement("h5", {
                      className: "card-title"
                    }, god.name), React.createElement("p", {
                      className: "card-text"
                    }, god.desc)));
}

var make = Card;

exports.make = make;
/* react Not a pure module */
