// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function godToJs(param) {
  return {
          name: param[/* name */0],
          desc: param[/* desc */1]
        };
}

function godFromJs(param) {
  return /* record */[
          /* name */param.name,
          /* desc */param.desc
        ];
}

exports.godToJs = godToJs;
exports.godFromJs = godFromJs;
/* No side effect */
