// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Base$ReactHooksTemplate = require("./Base.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Base$ReactHooksTemplate.make, { }), "base");

/*  Not a pure module */
